Fail if keys not found

diff --git a/.github/workflows/codesign.yml b/.github/workflows/codesign.yml
--- a/.github/workflows/codesign.yml
+++ b/.github/workflows/codesign.yml
@@ -31,22 +31,20 @@ jobs:
           APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
         run: |
           if [ -z "$APPLE_CERT_DATA" ] || [ -z "$APPLE_API_KEY" ]; then
-            echo "::notice:Skipped signing - missing Apple signing certificate or API key."
+            echo "::error::Codesign failed - missing Apple signing certificate or API key."
+            exit 1
           else
             echo "$APPLE_CERT_DATA" | base64 --decode > ${{ env.APPLE_CERT_PATH }}
             echo "$APPLE_API_KEY" | base64 --decode > ${{ env.APPLE_API_KEY_PATH }}
-            echo "PROCEED=1" >> $GITHUB_ENV
           fi
 
       - name: Download artifact
-        if: env.PROCEED
         uses: actions/download-artifact@v4
         with:
           name: sentry-godot-gdextension
           path: artifact/
 
       - name: Sign binaries
-        if: env.PROCEED
         run: |
           rcodesign sign --for-notarization \
             --p12-file ${{ env.APPLE_CERT_PATH }} --p12-password ${{ secrets.APPLE_CERT_PASSWORD }} \
@@ -60,7 +58,6 @@ jobs:
             artifact/addons/sentrysdk/bin/macos/crashpad_handler
 
       - name: Notarize binaries
-        if: env.PROCEED
         run: |
           # notarize_cmd=rcodesign notary-submit \
           #   --api-key-file ${{ env.APPLE_API_KEY_PATH }} \
@@ -71,7 +68,6 @@ jobs:
           # ${notarize_cmd} artifact/addons/sentrysdk/bin/macos/crashpad_handler
 
       - name: Upload artifact
-        if: env.PROCEED
         uses: actions/upload-artifact@v4
         with:
           name: sentry-godot-gdextension
